
import Navbar from '@/components/Navbar'
import './globals.css'
import Hero from '@/components/Hero'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='relative z-0 bg-primary'>
         
          <Navbar/>
            
          {children}
        </div>
      </body>
    </html>
  )
}

